services:
  - type: web
    name: tiny-living-market
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        fromContext: git_url
    disks:
      - name: tinyliving-uploads
        mountPath: /opt/render/project/src/public/uploads
        sizeGB: 1
      - name: tinyliving-db
        mountPath: /opt/render/project/src/storage/db
        sizeGB: 1
